### ISSUE TITLE
OAuth requests through OIDC/OAuth client extensions to Eclipse OAuth fail 

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#179]
Eclipse OAuth server does not follow spec perfectly, which causes failures in more brittle strongly typed systems (like the quarkus-oidc-client extension). The value for expires_in should be cast as an int rather than a String in a pure implementation of the specification.

Alternatives to solve this issue are as follows:

1. To change the endpoint to have the properly cast value. This has the consequence that it might impact other running services that rely on the current format.
2. To proxy a request through Keycloak which would likely have a better system to handle the differences.
3. To implement this functionality ourselves to better handle this case.

OAuth access token spec: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4

Stack trace:
```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at io.vertx.core.json.JsonObject.getLong(JsonObject.java:180)
	at io.quarkus.oidc.client.runtime.OidcClientImpl.emitGrantTokens(OidcClientImpl.java:110)
	at io.quarkus.oidc.client.runtime.OidcClientImpl.access$700(OidcClientImpl.java:30)
	at io.quarkus.oidc.client.runtime.OidcClientImpl$1.lambda$get$0(OidcClientImpl.java:98)
```

Failing Quarkus extension code, line highlighted with `>`:
```
    private Tokens emitGrantTokens(HttpResponse<Buffer> resp, boolean refresh) {
        if (resp.statusCode() == 200) {
            LOG.debugf("%s OidcClient has %s the tokens", oidcConfig.getId().get(), (refresh ? "refreshed" : "acquired"));
            JsonObject json = resp.bodyAsJsonObject();
            final String accessToken = json.getString(oidcConfig.grant.accessTokenProperty);
            final String refreshToken = json.getString(oidcConfig.grant.refreshTokenProperty);
            Long accessTokenExpiresAt;
>>>         Long accessTokenExpiresIn = json.getLong(oidcConfig.grant.expiresInProperty);
            if (accessTokenExpiresIn != null) {
                accessTokenExpiresAt = Instant.now().getEpochSecond() + accessTokenExpiresIn;
            } else {
                accessTokenExpiresAt = getExpiresJwtClaim(accessToken);
            }
            return new Tokens(accessToken, accessTokenExpiresAt, oidcConfig.refreshTokenTimeSkew.orElse(null), refreshToken);
        } else {
            String errorMessage = resp.bodyAsString();
            LOG.debugf("%s OidcClient has failed to complete the %s grant request:  status: %d, error message: %s",
                    oidcConfig.getId().get(), (refresh ? OidcConstants.REFRESH_TOKEN_GRANT : grantType), resp.statusCode(),
                    errorMessage);
            throw new OidcClientException(errorMessage);
        }
    }
```

**Comment by chrisguindon** [comment]
@autumnfound Can we close this now that you can fetch the info you need from keycloak?

**Comment by autumnfound** [comment]
Yeah we can. Its something we should think about in the future but it no longer blocks this project
